### ISSUE TITLE
image的全部图片资源在哪获取

### ISSUE THREAD

**Issue by ABKQPO** [LingerJAB/DanceCubeBot#1]

**Comment by LingerJAB** [comment]
谢谢提醒，现在已经发布到[Release](https://github.com/LingerJAB/DanceCubeBot/releases/tag/v1.1.0)了，请自行添加下载！

> 事实上，发送封面时DanceCubeBot会自动检索本地已有的封面图片，对于本地不存在的素材会从舞立方服务器发送请求，见[这里](https://github.com/LingerJAB/DanceCubeBot/blob/bf153b13b30139a9b7dce0c2f03b6524369d22e0/src/main/java/com/dancecube/music/GoodsMusic.java#L70C77-L70C77)  
> 当然，官谱会不定期更新，你也可以自行下载并添加新谱面的封面图片

**Comment by LingerJAB** [comment]
在`MusicUtil.getMusic()`会返回一个歌曲对象，会包含封面URL，在战力分析中会自动下载
