### ISSUE TITLE
使用Overflow的Mirai插件实现方法无法使用除登录外的任何功能

### ISSUE THREAD

**Issue by N1ngYu** [LingerJAB/DanceCubeBot#2]
使用mydc时会狠狠的报错....
像这样↓↓↓↓
![image](https://github.com/user-attachments/assets/2877a526-c31c-498d-b0bb-67872c711321)

在使用战力分析时则不会有任何反应...
_跟死掉了一样..._
(有反应，但止步于计算，见下)
![image](https://github.com/user-attachments/assets/931b8e6e-4057-4ad7-9aa5-9943e741eda4)
不知道是什么bug呢...

只有登录能玩（（（

机台登录尚未测试，但使用release中的1.2.0版本执行「强制刷新Token」等指令是没有反应的，后台也非常的寂静

**Comment by LingerJAB** [comment]
> 开发者没接触过Overflow，不知道会不会可能是Mirai解析的造成问题

以下是已知的原因：
- mydc报错会在下一个版本中修复，原因可能是新号，无法解析出胜率
- 强制刷新token暂时不可用，因为只能由开发者操作，因为还没有做出开发者配置所以就被写死在代码中了，或许下下个版本中优化🤔
- ***战力分析能不能把报错截图全一点***

**Comment by N1ngYu** [comment]
我觉得应该不太可能是overflow的解析问题 因为overflow的插件实现应该和mirai是一样的吧...？
（顺带问一下现在的mirai框架真的可以稳定运行qqbot嘛...会风控的吧 还是除了overflow有其他的实现）

呃战力分析其实没有报错 下面那个红色的真不是
战力分析的报错...也就是在回复一条「正在计算」后就再也没有消息了...

![image](https://github.com/user-attachments/assets/b54b7197-43f1-4b54-8d15-e86a048a5b2a)
（上面的报错不是战力分析的，是mydc的报错）
这是完整的图片 mcl其实我没有试过 因为怕风控而且也懒得整mirai的那一套gocq了

**Comment by LingerJAB** [comment]
我现在用了算是相对稳定的签名服务器，起码不会出现code45的问题了，不过很奇怪每次舞小铃初次使用必须删好友才能使用，我也很难确定这是不是风控的表现🤔

战力分析的过程：
1. 发送“正在计算”
2. 获取个人b15 r15
3. 下载封面，绘制分析图
4. 发送分析图

我遇到没反应大多数是在下载封面和绘制分析图处，这个速度取决于宽带大小和线程占用，但理论上来说只会拖慢速度而不是没有反应，如果你试了多个账号都是这个情况的话还是等我发布1.3.0版本吧

> 最近舞小铃没开就是有点忙，也在捣鼓更新的事情，1.3.0会重绘战力分析图，优化线程结构和报错😰我尽量在这两天发布

**Comment by N1ngYu** [comment]
好好好 我是llonebot协议 所以基本不会风控
我是挂在家用机上的 所以宽带大小基本不是问题
_总不能说是我接了三个框架的原因吧_
我的终端挂了一天始终是没有报错和反应的... 我还是等1.3.0吧
**辛苦了！**

**Comment by LingerJAB** [comment]
我发布了v1.2.1版本，你可以试试还是否可用
**配置文件要改一下**，***把Material改成UserRatioImage***，另外由于配置文件是在Mirai启动时加载的，可以看看启动的时候有没有报错或者一些其他提示

另外发不出消息也有可能是签名服务器的问题，可以尝试排查

~~github有时候不能及时回复，可以加我QQ*(QID:LingerJAB)*以更好解决~~

**Comment by N1ngYu** [comment]
已经更新v1.2.1，mydc的相关问题已经修复，但战力分析的bug还是缠着我不放

_bug是这样的，只需要缠着我们不放就好了，而我们开发者和使用者要考虑的就多了_

Mirai启动时我仔细看了一下，满屏绿，没有任何报错的，但是战力分析还是原来的问题啊..（指无下文），估计是获取不到r15b15？又或者是我的号比较新的原因？（因为下载的图片缓存我在本地文件都找到了，但就是没有反应）
![image](https://github.com/user-attachments/assets/8481ee00-7049-462b-857d-5948f3b8934c)
总不能是不支持3代机数据吧...


签名服务器和风控这些我觉得应该都不是问题，因为overflow是直接走的onebot，也就是直接从q官方客户端发送，不太存在风控的风险 _tx不至于不认自家软件吧_

最后问一下菜单的回复能否改回原来的样子...因为非插件官方bot所以...没有菜单图（没有也是可以的啦 我把之前的那个截个图塞主页也能凑合凑合）

**Comment by N1ngYu** [comment]
8/29
今天在和本地群群友偶然测试bot的时候发现插件竟然自己偷偷好了...
现在战力分析图可以正常获取了..我也不知道为什么它就突然能用了 很莫名奇妙
总之就是现在可以用了...我也没改什么东西...莫名奇妙就好了
先close了吧 有问题日后再解决（
